### ISSUE TITLE
Add support for Profiles to modify behaviour for different environments

### ISSUE THREAD

**Issue by yamaduc** [Chorus-bdd/Chorus#32]
We have a case, where we need the process handler, to handle a particular situation.

For example, in the Feature-Start: 

I want to check if something is running already and it wasn't started by Chorus.
I could create a handler to check if the outside process is running.
If it is running, create a new ChorusContext variable, isRunning, and set it to true.
If it's not running, create a new ChorusContext variable, isRunning, and set it to false.

Add a new step to the Process Handler to check the ChorusContext variable isRunning.

If isRunning is not null/false, then start the process.
If isRunning is true, don't start the process.

This would be useful where you have 2 situations.

E.G. 1 
The developer doesn't want to start a server, wants the test framework to start the server and run all tests on their local machine.

E.G. 2
The qa setup has an external process which deploys and starts the server in a vm and qa only wants the tests to run.

**Comment by nickebbutt** [comment]
This is done for config variables

We will shortly add support for extra .profile files which can contain scenarios to help set up or tear down the test environment for a specific profile
